//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kunde
    {
        public int KNR { get; set; }
        public string Name { get; set; }
        public string Ort { get; set; }
        public Nullable<decimal> Gehalt { get; set; }
    }
}
